#!/bin/sh /etc/rc.common
# Cerberus network monitor

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/cerberusd

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" \
        -config /etc/cerberus/cerberus.json \
        -listen :8443
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/cerberusd.pid
    procd_close_instance
}

stop_service() {
    killall cerberusd 2>/dev/null
}

reload_service() {
    stop
    start
}
