#!/bin/sh
# Cerberus first-boot configuration
# Runs once on first boot, then deletes itself

# Set hostname
uci set system.@system[0].hostname='Cerberus'
uci commit system

# Set root password to "toor"
echo -e "toor\ntoor" | passwd root

# Set timezone (UTC by default, user can change)
uci set system.@system[0].zonename='UTC'
uci commit system

# Enable IP forwarding
uci set network.globals.ip_forward='1'
uci commit network

# Make sure Cerberus starts on boot
/etc/init.d/cerberus enable 2>/dev/null

echo "Cerberus first-boot complete."
exit 0
